# Generated by Django 5.2.7 on 2025-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=30)),
                ('conteudo', models.CharField(max_length=60)),
                ('data', models.DateField()),
            ],
        ),
    ]
