# Generated by Django 5.2.7 on 2025-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='id',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='pessoa',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
