# Generated by Django 5.2.7 on 2025-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_mensagem_id_alter_mensagem_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
