# Generated by Django 5.2.7 on 2025-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mensagem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='pessoa',
            field=models.CharField(max_length=30),
        ),
    ]
