# Generated by Django 5.2.7 on 2025-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mensagem_id_alter_mensagem_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
